### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by MarkMjw** [zjupure/GlideWebpDecoder#2]
使用场景：Tabhost+Fragment+RecyclerView(Grid)
切换界面，通过view.setVisibilityChangeListener监听View的显示状态，通过WebpDrawable来控制动画播放，来回滑动列表几次很容易出现这个崩溃。
日志如下：
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.bumptech.glide.integration.webp.WebpImage.getFrameCount()' on a null object reference
                                                                                       at com.bumptech.glide.integration.webp.decoder.WebpDecoder.getFrameCount(WebpDecoder.java:120)
                                                                                       at com.bumptech.glide.integration.webp.decoder.WebpFrameLoader.getFrameCount(WebpFrameLoader.java:136)
                                                                                       at com.bumptech.glide.integration.webp.decoder.WebpDrawable.startRunning(WebpDrawable.java:154)
                                                                                       at com.bumptech.glide.integration.webp.decoder.WebpDrawable.start(WebpDrawable.java:142)

另外，CPU占用挺高的，不知道能否优化。

**Comment by zjupure** [comment]
@MarkMjw Can you provide some sample code to reproduce this issue? As I see, you have no need to use `WebpDrawable` directly. `WebpDrawable` will  start or stop animation according to the view visibility.   Show how you use the WebpDrawable. The crash seems to that the view has been destroyed and related `WebpDrawable`  is recycled by Glide auto. Then you hold the recycled `WebpDrawable`reference and try to reuse it.

As for high cpu usage issue, webp decode operations are behind the background thread and foreground thread will only do UI rending. Can you provide some more information such as how many animated webp images display in one screen at the same time and detail cpu usages?

**Comment by Acoee** [comment]
It's also happened in my project.

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
        at com.bumptech.glide.integration.webp.decoder.WebpFrameLoader.getWidth(WebpFrameLoader.java:135)
        at com.bumptech.glide.integration.webp.decoder.WebpDrawable.getIntrinsicWidth(WebpDrawable.java:194)
        at android.widget.ImageView.invalidateDrawable(ImageView.java:232)
        at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:390)
        at android.graphics.drawable.Drawable.setVisible(Drawable.java:769)
        at com.bumptech.glide.integration.webp.decoder.WebpDrawable.setVisible(WebpDrawable.java:190)
        at android.widget.ImageView.onDetachedFromWindow(ImageView.java:1485)
        at android.view.View.dispatchDetachedFromWindow(View.java:14762)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3191)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3191)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3191)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3191)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3191)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3191)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3191)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3191)
        at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3556)
        at android.view.ViewRootImpl.doDie(ViewRootImpl.java:6285)
        at android.view.ViewRootImpl.die(ViewRootImpl.java:6257)
        at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:459)
        at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:414)
        at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4154)
        at android.app.ActivityThread.access$1700(ActivityThread.java:178)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1571)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5845)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)

**Comment by zjupure** [comment]
@Acoee this crash should have been fixed in commit [2f786ac1](https://github.com/zjupure/GlideWebpDecoder/commit/2f786ac1e5f9d8fba04c41875a31e9144d6c28cd)
