### ISSUE TITLE
There are some exceptions on Android 9.0 when app started

### ISSUE THREAD

**Issue by liusgh** [zjupure/GlideWebpDecoder#35]
Hello developers:
On Android 9.0 I found some exception information when app started, the stack is as follows:
```java
03-15 16:18:13.307 26854-26854/com.xxx.xxx:dcs W/SoLoader: Cannot get nativeLoad method
    java.lang.NoSuchMethodException: nativeLoad [class java.lang.String, class java.lang.ClassLoader, class java.lang.String]
        at java.lang.Class.getMethod(Class.java:2068)
        at java.lang.Class.getDeclaredMethod(Class.java:2047)
        at com.facebook.soloader.SoLoader.getNativeLoadRuntimeMethod(SoLoader.java:281)
        at com.facebook.soloader.SoLoader.initSoLoader(SoLoader.java:233)
        at com.facebook.soloader.SoLoader.initImpl(SoLoader.java:141)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:120)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:104)
        at com.xxx.xxx.impl.webp.WebpResourceDecoder.<init>(WebpResourceDecoder.java:54)
        at com.xxx.xxx.base.xxx.registerComponents(xxx.java:77)
        at com.bumptech.glide.GeneratedAppGlideModuleImpl.registerComponents(GeneratedAppGlideModuleImpl.java:32)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:269)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:219)
        at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:180)
        at com.bumptech.glide.Glide.get(Glide.java:164)
        ...
```
You may be confused that some classes( For example, WebpResourceDecoder) are not in your project.
In fact, our project integrates your project and GlideWebpSupport (https://github.com/roths/GlideWebpSupport) in a sourcecode-dependent way. We replaced the WebpDecoder and WebpFrameLoader classes in your project with the same-named classes in the GlideWebpSupport project (because we found some problems with the GlideWebpSupport project).

My question is what would be the risk of this error if not handled, because we have not found any abnormality in the loading of dynamic webp.
Due to the lack of familiarity with fresco and c++ mechanisms, I would like to ask if it is necessary to deal with this error, because we only use fresco to load dynamic webp.

Many thanks.

**Comment by zjupure** [comment]
```
at com.facebook.soloader.SoLoader.init(SoLoader.java:104)
at com.xxx.xxx.impl.webp.WebpResourceDecoder.<init>(WebpResourceDecoder.java:54)
```

`GlideWebpDecoder` do not use WebpResourceDecoder and Soloader library, It seems like Soloader call an API that has been removed in Android P.
see https://github.com/facebook/SoLoader/commit/4995a4bc2de148a4a6e5a9544f8f47b5dc819de9#diff-af2278b3b6db94229f8e96a1f3862dbd, comment: the third argument of nativeLoad method was removed in Android P API.

You should update the soloader library version to avoid the risk, thanks.
