### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by raylee4204** [zjupure/GlideWebpDecoder#4]
`
03-28 21:27:13.863 21015-21015/com.bunz.dev I/Glide: Root cause (1 of 1)
    java.lang.NoSuchMethodError: No direct method <init>(I)V in class Lcom/bumptech/glide/util/LruCache; or its super classes (declaration of 'com.bumptech.glide.util.LruCache' appears in /data/app/com.sample-2/split_lib_directories_apk.apk)
        at com.bumptech.glide.integration.webp.decoder.WebpDecoder.<init>(WebpDecoder.java:72)
        at com.bumptech.glide.integration.webp.decoder.ByteBufferWebpDecoder.decode(ByteBufferWebpDecoder.java:73)
        at com.bumptech.glide.integration.webp.decoder.ByteBufferWebpDecoder.decode(ByteBufferWebpDecoder.java:30)
        at com.bumptech.glide.integration.webp.decoder.StreamWebpDecoder.decode(StreamWebpDecoder.java:61)
        at com.bumptech.glide.integration.webp.decoder.StreamWebpDecoder.decode(StreamWebpDecoder.java:24)
        at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:72)
        at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:55)
        at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:45)
        at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:58)
        at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:43)
        at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:498)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:469)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:455)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:407)
        at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:376)
        at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:112)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:133)
        at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:52)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:97)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:299)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:269)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
`

Possibly because of using older version of Glide?

**Comment by zjupure** [comment]
current version 0.0.6 can only work with glide 4.2.0. If you use a higher glide version, the issue is produced. I will update the library to follow the latest glide version.

**Comment by zjupure** [comment]
@raylee4204 please update version to 0.0.7.{glide_version} to solve this issue. see README for more information.
