### ISSUE TITLE
 Unable to convert com.bumptech.glide.integration.webp.decoder.WebpDrawable@4e4c26c to a Bitmap

### ISSUE THREAD

**Issue by XunMengWinter** [zjupure/GlideWebpDecoder#6]
在demo上可以加在网络webp动图，但在我们公司项目上加载不了（只能加载常规webp图片），好神奇，报错日志如下。

06-28 16:51:02.142 2591-2827/com.hdwawa.claw E/GlideExecutor: Request threw uncaught throwable
    java.lang.IllegalArgumentException: Unable to convert com.bumptech.glide.integration.webp.decoder.WebpDrawable@4e4c26c to a Bitmap
        at com.bumptech.glide.load.resource.bitmap.DrawableTransformation.transform(DrawableTransformation.java:56)
        at com.bumptech.glide.load.engine.DecodeJob.onResourceDecoded(DecodeJob.java:534)
        at com.bumptech.glide.load.engine.DecodeJob$DecodeCallback.onResourceDecoded(DecodeJob.java:598)
        at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:46)
        at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:58)
        at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:43)
        at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:501)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:472)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:458)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:410)
        at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:379)
        at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:135)
        at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:95)
        at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:74)
        at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:49)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:272)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)

**Comment by XunMengWinter** [comment]
最后用覆盖的方式解决了圆角问题～

**Comment by zjupure** [comment]
动图webp解码出来的是WebpDrawable对象，无法转换成Bitmap的，你可以自己实现Transformation<WebpDrawable>接口实现圆角效果，设置到Glide的请求上。这个和Gif动图一样，都需要自己处理圆角。

**Comment by zijinzhiyun** [comment]
@zjupure 如何实现webp 动图的圆角呢？为什么不解码成bitmap呢，这样可以结合glide-transformations库更方便的对图片进行转换，否则，需要自己实现毛玻璃等效果，感谢

**Comment by zjupure** [comment]
see #8 Use `WebpDrawableTransformation` to wrap your original BitmapTransformation, it is not Glide build-in, so you need add code with Glide load.

**Comment by zjupure** [comment]
#8
