### ISSUE TITLE
ANR when decode webp in glide

### ISSUE THREAD

**Issue by cursem** [zjupure/GlideWebpDecoder#88]
"main" prio=5 tid=1 Blocked
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x74960540 self=0x7dd7c10800
  | sysTid=30332 nice=-8 cgrp=default sched=0/0 handle=0x7e5eb1c0d0
  | state=S schedstat=( 8607810413 205146354 12473 ) utm=693 stm=167 core=5 HZ=100
  | stack=0x7ffd093000-0x7ffd095000 stackSize=8192KB
  | held mutexes=
  at com.bumptech.glide.util.LruCache.put(LruCache.java:-1)
  - waiting to lock <0x0e717388> (a com.bumptech.glide.load.engine.cache.LruResourceCache) held by thread 170
  at com.bumptech.glide.load.engine.cache.LruResourceCache.put(LruResourceCache.java:11)
  at com.bumptech.glide.load.engine.Engine.onResourceReleased(Engine.java:438)
  at com.bumptech.glide.load.engine.EngineResource.release(EngineResource.java:116)
  at com.bumptech.glide.load.engine.Engine.release(Engine.java:398)
  at com.bumptech.glide.request.SingleRequest.clear(SingleRequest.java:373)
  at com.bumptech.glide.manager.RequestTracker.clearAndRemove(RequestTracker.java:72)
  at com.bumptech.glide.RequestManager.untrack(RequestManager.java:664)
  - locked <0x0ab1d121> (a com.vega.glide.GlideRequests)
  at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:632)
  at com.bumptech.glide.RequestManager.clear(RequestManager.java:628)
  at com.bumptech.glide.integration.webp.decoder.WebpFrameLoader.clear(WebpFrameLoader.java:188)
  at com.bumptech.glide.integration.webp.decoder.WebpDrawable.recycle(WebpDrawable.java:297)
  at com.bumptech.glide.integration.webp.decoder.WebpDrawableResource.recycle(WebpDrawableResource.java:25)
  at com.bumptech.glide.load.engine.EngineResource.recycle(EngineResource.java:75)
  - locked <0x0bf44946> (a com.bumptech.glide.load.engine.EngineResource)
  at com.bumptech.glide.load.engine.ResourceRecycler$ResourceRecyclerCallback.handleMessage(ResourceRecycler.java:37)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loop(Looper.java:219)
  at android.app.ActivityThread.main(ActivityThread.java:8668)
  at java.lang.reflect.Method.invoke(Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

"glide-decode-thread-1" prio=5 tid=170 Blocked
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x13b82548 self=0x7c10646400
  | sysTid=30735 nice=9 cgrp=default sched=0/0 handle=0x7c175d7d50
  | state=S schedstat=( 148174481 39856771 185 ) utm=14 stm=0 core=5 HZ=100
  | stack=0x7c174d5000-0x7c174d7000 stackSize=1039KB
  | held mutexes=
  at com.bumptech.glide.RequestManager.untrack(RequestManager.java:-1)
  - waiting to lock <0x0ab1d121> (a com.vega.glide.GlideRequests) held by thread 1
  at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:632)
  at com.bumptech.glide.RequestManager.clear(RequestManager.java:628)
  at com.bumptech.glide.integration.webp.decoder.WebpFrameLoader.clear(WebpFrameLoader.java:192)
  at com.bumptech.glide.integration.webp.decoder.WebpDrawable.recycle(WebpDrawable.java:297)
  at com.bumptech.glide.integration.webp.decoder.WebpDrawableResource.recycle(WebpDrawableResource.java:25)
  at com.bumptech.glide.load.engine.EngineResource.recycle(EngineResource.java:75)
  - locked <0x0a3c1e64> (a com.bumptech.glide.load.engine.EngineResource)
  at com.bumptech.glide.load.engine.ResourceRecycler.recycle(ResourceRecycler.java:22)
  - locked <0x023398cd> (a com.bumptech.glide.load.engine.ResourceRecycler)
  at com.bumptech.glide.load.engine.Engine.onResourceRemoved(Engine.java:431)
  at com.bumptech.glide.load.engine.cache.LruResourceCache.onItemEvicted(LruResourceCache.java:31)
  at com.bumptech.glide.load.engine.cache.LruResourceCache.onItemEvicted(LruResourceCache.java:11)
  at com.bumptech.glide.util.LruCache.trimToSize(LruCache.java:174)
  - locked <0x0e717388> (a com.bumptech.glide.load.engine.cache.LruResourceCache)
  at com.bumptech.glide.util.LruCache.pN(LruCache.java:179)
  at com.bumptech.glide.util.LruCache.put(LruCache.java:134)
  - locked <0x0e717388> (a com.bumptech.glide.load.engine.cache.LruResourceCache)
  at com.bumptech.glide.load.engine.cache.LruResourceCache.put(LruResourceCache.java:11)
  at com.bumptech.glide.load.engine.Engine.onResourceReleased(Engine.java:438)
  at com.bumptech.glide.load.engine.EngineResource.release(EngineResource.java:116)
  at com.bumptech.glide.load.engine.EngineJob.pw(EngineJob.java:321)
  at com.bumptech.glide.load.engine.EngineJob.notifyCallbacksOfException(EngineJob.java:292)
  at com.bumptech.glide.load.engine.EngineJob.onResourceReady(EngineJob.java:349)
  at com.bumptech.glide.load.engine.DecodeJob.notifyComplete(DecodeJob.java:359)
  at com.bumptech.glide.load.engine.DecodeJob.notifyEncodeAndRelease(DecodeJob.java:480)
  at com.bumptech.glide.load.engine.DecodeJob.getFetcherReadyCallback(DecodeJob.java:461)
  at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:299)
  at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:249)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  at java.lang.Thread.run(Thread.java:929)
  at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:449)

**Comment by 364089999** [comment]
我也碰到了这种死锁问题；
1：线程1加载资源，触发WebFrameLoader释放资源，先获取Lru的锁，最后触发调用RequestManager.untrack()方法，等待RequestManare获取对象锁；
2：线程2WebFrameLoader先触发释放资源，调用RequestManager.untrack()，获取RequestManger对象锁，触发调用Lru导入remove方法，等待Lru对象锁
上面两个线程出现死锁等待现象。

**Comment by zjupure** [comment]
locked <0x0ab1d121> (a com.vega.glide.GlideRequests)
com.vega.glide.GlideRequests这个是你们自定义的类？这里死锁了，跟Webp Decoder没关系
